name: My First Github Action
on: [push]
jobs:
  buildApp:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text }}
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Sets the vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\"}" > project.json
      - name: Deploying the project
        run: yarn deploy
      - name: Setup finish
        id: finished
        run: echo "::set-output name=text::hello-world-from-build-job"
  test-app:
    needs: buildApp
    runs-on: ubuntu-latest
    env:
      MY_JOB_OUTPUT: ${{ needs.buildApp.outputs.text }}
    steps:
      - run: echo MY_JOB_OUTPUT
